# Node.js with React
- task: netsparker-cloud@1
  inputs:
    apiConnection: 'azuredevopstest'
    scanTypes: '2'
    scanWebSites: '2e1498ff-ad9a-4569-c4e4-ae8301b8e800'
    scanWebSitesProfile: 'be7bc50f-e79d-4954-7b0a-af0402ac06ea'
    buildFail: true
    severity: 'Critical,High'
    stopScan: true
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
