- task: netsparker-cloud@1
  inputs:
    apiConnection: 'Test for Invicti'
    scanTypes: '2'
    scanWebSites: 'b45e158b-7190-4934-6d65-aefd033fcdb6'
    scanWebSitesProfile: 'e9cd2191-59a7-4857-b31b-af0f02f58869'
    buildFail: true
    severity: 'DoNotFail'